include:
  - path: ./docker-compose.milvus.yml

services:
  # api_server:
  #   container_name: "api_server"
  #   build:
  #     context: ../backend
  #     dockerfile: Dockerfile
  #   restart: always
  #   env_file:
  #     - ../.env
  #   ports:
  #     - 8000:8000
  postgres:
      image: postgres:18-alpine3.23
      container_name: postgres
      restart: always
      environment:
        - POSTGRES_USER=${POSTGRES_USER:-postgres}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
        - POSTGRES_DB=${POSTGRES_DB:-postgres}
      env_file:
        - ../.env
      ports:
        - 5432:5432
      volumes:
        - postgres_data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}'"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 10s
  minio_local:
    image: minio/minio:latest
    container_name: minio_local
    environment:
      - MINIO_ROOT_USER=abcd
      - MINIO_ROOT_PASSWORD=abcd2345
      - MINIO_DEFAULT_BUCKET=buck1
    command: minio server /minio_data --console-address ":9001"
    volumes:
      - minio_data_local:/data
    ports:
      - "7000:9000"
      - "7001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  postgres_data:
  minio_data_local:
